Fairness/: add timeout

diff --git a/Fairness/runFancy b/Fairness/runFancy
--- a/Fairness/runFancy
+++ b/Fairness/runFancy
@@ -1,15 +1,36 @@
 #!/bin/bash
 
+TIMEOUT=5
+
 # Check the number of command-line arguments
 if [ \( "$#" -eq 0 \) ] ; then
-	echo "usage: ${0} [--silent] <file> [params]"
+	echo "usage: ${0} [--silent] [-t timeout] <file> [params]"
+	echo "  --silent     Do not print diagnostic messages"
+	echo "  -t timeout   Set the timeout (default: ${TIMEOUT} s; 0 = infinity)"
 	exit 1
 fi
 
-if [ "$1" == "--silent" ] ; then
-	SILENT="1"
-	shift
-fi
+while [[ $# -gt 0 ]] ; do
+	case $1 in
+		--silent)
+		SILENT="1"
+		;;
+		-t|--timeout)
+		TIMEOUT="$2"
+		shift # past value
+		;;
+		*)    # other
+		if [ -z "${SRC}" ] ; then
+			SRC=${1}
+		else
+			echo "error: input file specified multiple times!"
+			exit 1
+		fi
+		;;
+	esac
+
+	shift # past argument
+done
 
 if [ $(uname) = "Linux" ]; then
     pathCmd="readlink -f"
@@ -19,7 +40,6 @@ elif [ $(uname) = "Darwin" ]; then
 else
     pathCmd="realpath"
 fi
-SRC="${1}"
 
 OUTPUT_DIR="./output"
 
@@ -33,8 +53,23 @@ if [ -z "${SILENT}" ] ; then
 	cd ${OUTPUT_DIR} && ./alltosvg && cd ..
 fi
 
+echo "Running ../LivenessProver/slrp ${SRC}" >&2
 # run the main script
-. ../LivenessProver/slrp
+if [ $TIMEOUT -eq 0 ] ; then   # no timeout
+	# . ../LivenessProver/slrp
+	../LivenessProver/slrp ${SRC}
+	rc=$?
+else
+	timeout ${TIMEOUT} ../LivenessProver/slrp ${SRC}
+	rc=$?
+fi
+
+if [ "$rc" -eq 124 ] ; then
+	echo "TIMEOUT" >&2
+elif [ "$rc" -ne 0 ] ; then
+	echo "other error (errno = $rc)"
+	exit 1
+fi
 
 if [ -z "${SILENT}" ] ; then
 	cp ${SRC} "${OUTPUT_DIR}/slrp_input.txt"
